// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qidbqjftdikiefsebeqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZGJxamZ0ZGlraWVmc2ViZXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNzc3ODQsImV4cCI6MjA5MDc1Mzc4NH0.R-jm3vnRxoR8DkXoJXhTlIlZATpP-uNqdMtmpuXB0OY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});